version: '3'
services:
  database-pg:
    build: ./docker/postgresql
    container_name: postgresql
    volumes:
      #- ./docker/postgresql/db/pgdata:/var/lib/postgresql/data
      - ./docker/postgresql/db/logs:/var/lib/postgresql/logs
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database-sample
      - PGDATA=$PGDATA
     