version: '3'
services:
  postgresql:
    build: ./docker/postgresql
    container_name: postgresql
    volumes:
      - ./docker/postgresql/db/pgdata:/pgdata
      - ./docker/postgresql/db/logs:/var/lib/postgresql/logs
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=go-rest-postgresql
      - PGDATA=$PGDATA
     