version: '3'
services:
  database:
    build: ./db
    container_name: rest-pg-db
    #restart: always
    volumes:
      - postgresql-volume:$PGDATA
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rest-pg
      - PGDATA=$PGDATA
      
volumes:
  postgresql-volume:
    external: true